name: BUILD AND DEPLOY VUEPRESS
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build and Deploy
        uses: jenkey2011/vuepress-deploy@v1.8.1
        env:
          ACCESS_TOKEN: ${{ secrets.TOKEN }}
          TARGET_REPO: coder-yyz/time-corner
          TARGET_BRANCH: vuepress-target
          # 新增源替换命令，再执行构建
          BUILD_SCRIPT: |
            sed -i 's/http:\/\/deb.debian.org\/debian/http:\/\/archive.debian.org\/debian/g' /etc/apt/sources.list
            sed -i '/deb http:\/\/archive.debian.org\/debian buster-updates main/d' /etc/apt/sources.list
            apt-get update && apt-get install -y git jq
            yarn && yarn build
          BUILD_DIR: docs/.vuepress/dist/
